const FW_APP_CONSTANTS = {
  APP_CUSTOM_OBJECT: 'CUSTOM-OBJECT',
  COMPONENT_CO_WIDGET_CARD: 'WIDGET-CARD',
  COMPONENT_FD_SEARCH_CARD: 'SEARCH-CARD',
  COMPONENT_TAG: {
    'WIDGET-CARD': 'fw-widget-card',
    'SEARCH-CARD': 'fw-search-card',
  },
  API_NAMESPACE: 'custom_objects',
  ACTION_NAVIGATE: 'NAVIGATE',
  SCHEMA_TYPE_NATIVE: 'NATIVE',
  SCHEMA_TYPE_CUSTOM: 'CUSTOM',
  SCHEMA_COMPANY: 'company',
  SCHEMA_CONTACT: 'contact',
  SCHEMA_TICKET: 'ticket',
  WIDGET_VARIATION_TICKET: 'ticket',
  WIDGET_VARIATION_CONTACT: 'contact',
  PRIMARY_FIELD: 'PRIMARY',
  FIELD_TYPE_DATE: 'DATE',
  FIELD_TYPE_CHECKBOX: 'CHECKBOX',
  FIELD_TYPE_PARAGRAPH: 'PARAGRAPH',
  FIELD_TYPE_MULTISELECT: 'MULTI_SELECT',
  FIELD_TYPE_RELATIONSHIP: 'RELATIONSHIP',
  LOOKUP_ONE_TO_ONE: 'ONE_TO_ONE',
  LOOKUP_MANY_TO_ONE: 'MANY_TO_ONE',
  MAX_WIDGET_RECORDS_DISPLAY_COUNT: 3,
  MAX_WIDGET_FIELDS_COUNT: 5,
  EMPTY_FIELD_VALUE: '-',
};

export default FW_APP_CONSTANTS;

export const APP_ID = 'stencilMFE1';
