/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FwSample1 {
        "trigger": (params: any) => Promise<{ response: { params: any; }; }>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "trigger": (params: any) => Promise<{ response: { params: any; }; }>;
    }
}
declare global {
    interface HTMLFwSample1Element extends Components.FwSample1, HTMLStencilElement {
    }
    var HTMLFwSample1Element: {
        prototype: HTMLFwSample1Element;
        new (): HTMLFwSample1Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fw-sample1": HTMLFwSample1Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FwSample1 {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fw-sample1": FwSample1;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fw-sample1": LocalJSX.FwSample1 & JSXBase.HTMLAttributes<HTMLFwSample1Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
